#pragma once

#include "pico/stdlib.h"
#include "hardware/pio.h"

// This header is automatically generated by CMake from the .pio file
#include "sk6812.pio.h"

// Predefined LED colors for consistent usage across the codebase
enum class LedColor : uint8_t {
    OFF,        // 0, 0, 0
    RED,        // 255, 0, 0
    GREEN,      // 0, 255, 0
    BLUE,       // 0, 0, 255
    YELLOW,     // 255, 255, 0
    ORANGE,     // 255, 120, 0
    MAGENTA,    // 255, 0, 255
};

class SK6812 {
private:
    uint _pin;
    bool _is_rgbw;
    PIO _pio;
    int _sm;      // State machine index
    uint _offset;  // Memory offset of the PIO program
    uint8_t _brightness;         // 0-255
    uint8_t _stored_r, _stored_g, _stored_b; // Target color
    
    // Blinking state
    bool _is_blinking;
    uint32_t _blink_interval_ms;
    uint32_t _last_blink_time;
    bool _blink_state_on;   // Is the LED currently in the ON phase?
    uint32_t _blink_duration_ms; 
    uint32_t _blink_start_time;

    /** * Internal helper to apply brightness and write to PIO.
     * Use this instead of direct pio_sm_put_blocking in public methods.
     */
    void _write(uint8_t r, uint8_t g, uint8_t b);

public:
    /**
     * @param pin GPIO pin number
     * @param pio The PIO block to use (pio0 or pio1)
     * @param is_rgbw True for SK6812 (RGBW), False for WS2812 (RGB)
     */
    SK6812(uint pin, PIO pio = pio0, bool is_rgbw = false);

    /** Initialize PIO and State Machine */
    bool init();

    /** * Set color. 
     * If blinking is active, this changes the color of the "ON" phase
     * but does not stop the blinking.
     */
    void setColor(uint8_t r, uint8_t g, uint8_t b, uint8_t brightness = 255);

    /** Set color from predefined enum. */
    void setColor(LedColor color, uint8_t brightness = 255);

    /** Set global brightness (0-255). Applies to current and future colors. */
    void setBrightness(uint8_t b);

    /** * Start blinking non-blocking.
     * @param interval_ms Duration of ON and OFF states in milliseconds
     */
    void startBlink(uint32_t interval_ms, uint32_t duration_ms = 0);

    /** Stop blinking and return to steady stored color. */
    void stopBlink();

    /** * Must be called in the main loop (while true) to handle blinking. 
     */
    void update();
    
    /** Turn off the LED */
    void off();
};