#pragma once

#include <stdint.h>

// Anti-aliased font data structures for 4-bit alpha rendering.
// Generated by tools/generate_font.py from TTF source files.

struct AAGlyph {
    uint8_t  width;      // Glyph bitmap width in pixels
    uint8_t  height;     // Glyph bitmap height in pixels
    int8_t   xOffset;    // X offset from cursor to bitmap left edge
    int8_t   yOffset;    // Y offset from origin to bitmap top edge
    uint8_t  xAdvance;   // Horizontal cursor advance after this glyph
    uint16_t dataOffset; // Byte offset into the font's packed bitmap array
};

struct AAFont {
    uint8_t  size;       // Nominal font size in pixels
    uint8_t  lineHeight; // Total line height (ascent + descent)
    uint8_t  ascent;     // Ascent from baseline to top
    char     firstChar;  // First character code in glyph array
    char     lastChar;   // Last character code in glyph array
    const AAGlyph* glyphs;  // Glyph metrics array (indexed by char - firstChar)
    const uint8_t* bitmap;  // Packed 4-bit alpha bitmap data (high nibble first)
};
