#!/usr/bin/env python3
"""
Font conversion tool for PD240W anti-aliased font rendering.

Renders a TTF font at a given pixel size into a C header file containing
4-bit alpha bitmap data for each glyph. The output is compatible with
the AAFont/AAGlyph structs in aa_font.h.

Usage:
    python generate_font.py <ttf_path> <pixel_size> <output_header> [--chars <charset>] [--name <font_name>]

Examples:
    python generate_font.py fonts/Inter-Bold.ttf 28 ../src/drivers/display/font_inter_28b.h --chars digits --name font_inter_28b
    python generate_font.py fonts/Inter-SemiBold.ttf 20 ../src/drivers/display/font_inter_20sb.h --name font_inter_20sb
    python generate_font.py fonts/Inter-Regular.ttf 12 ../src/drivers/display/font_inter_12.h --name font_inter_12

Requires: pip install Pillow
"""

import argparse
import os
import sys
from PIL import Image, ImageDraw, ImageFont


# Predefined character sets
CHARSET_ASCII = [chr(c) for c in range(32, 127)]  # space through ~
CHARSET_DIGITS = list(" 0123456789.:VAWmM-/%()")


def render_glyph(font, char, size):
    """Render a single character and return its alpha bitmap + metrics."""
    # Get the bounding box of the glyph
    # Use getbbox on a large canvas to find actual ink bounds
    canvas_size = size * 3
    img = Image.new('L', (canvas_size, canvas_size), 0)
    draw = ImageDraw.Draw(img)

    # Draw at a known position
    origin_x = size
    origin_y = size
    draw.text((origin_x, origin_y), char, font=font, fill=255)

    # Find the bounding box of non-zero pixels
    bbox = img.getbbox()
    if bbox is None:
        # Space or empty glyph - return empty bitmap with correct advance
        # Get advance width
        left, top, right, bottom = font.getbbox(char)
        advance = right - left
        if advance == 0:
            advance = size // 4  # fallback for space
        return {
            'width': 0,
            'height': 0,
            'xOffset': 0,
            'yOffset': 0,
            'xAdvance': max(1, advance),
            'bitmap': [],
        }

    # Crop to bounding box
    x0, y0, x1, y1 = bbox
    glyph_img = img.crop(bbox)

    # Calculate offsets relative to the drawing origin
    x_offset = x0 - origin_x
    y_offset = y0 - origin_y

    # Get advance width using getlength for accurate measurement
    try:
        advance = int(round(font.getlength(char)))
    except AttributeError:
        left, top, right, bottom = font.getbbox(char)
        advance = right - left

    # Get pixel data and quantize to 4 bits (0-15)
    pixels = list(glyph_img.getdata())
    width = glyph_img.width
    height = glyph_img.height

    alpha_4bit = []
    for p in pixels:
        # Map 0-255 to 0-15
        a = (p * 15 + 127) // 255
        alpha_4bit.append(a)

    return {
        'width': width,
        'height': height,
        'xOffset': x_offset,
        'yOffset': y_offset,
        'xAdvance': max(1, advance),
        'bitmap': alpha_4bit,
    }


def pack_4bit(alpha_list):
    """Pack a list of 4-bit values into bytes (high nibble first)."""
    packed = []
    for i in range(0, len(alpha_list), 2):
        hi = alpha_list[i] & 0x0F
        lo = alpha_list[i + 1] & 0x0F if i + 1 < len(alpha_list) else 0
        packed.append((hi << 4) | lo)
    return packed


def generate_header(font_path, pixel_size, output_path, charset, font_name):
    """Generate a C header file with font data."""
    # Load the font
    font = ImageFont.truetype(font_path, pixel_size)

    # Get font metrics for baseline
    ascent, descent = font.getmetrics()

    # Render all glyphs
    glyphs = {}
    for char in charset:
        glyphs[char] = render_glyph(font, char, pixel_size)

    # Build packed bitmap array
    bitmap_data = []
    for char in charset:
        g = glyphs[char]
        g['data_offset'] = len(bitmap_data)
        packed = pack_4bit(g['bitmap'])
        bitmap_data.extend(packed)

    # Determine char range
    first_char = min(ord(c) for c in charset)
    last_char = max(ord(c) for c in charset)

    # Build glyph array (indexed by char - first_char)
    # Fill gaps with empty glyphs
    glyph_array = []
    charset_set = set(charset)
    for code in range(first_char, last_char + 1):
        char = chr(code)
        if char in charset_set:
            g = glyphs[char]
            glyph_array.append(g)
        else:
            # Empty placeholder
            glyph_array.append({
                'width': 0, 'height': 0,
                'xOffset': 0, 'yOffset': 0,
                'xAdvance': pixel_size // 4,
                'data_offset': 0,
            })

    # Generate the C header
    guard = font_name.upper() + '_H'
    lines = []
    lines.append(f'#pragma once')
    lines.append(f'')
    lines.append(f'// Auto-generated by generate_font.py')
    lines.append(f'// Font: {os.path.basename(font_path)} @ {pixel_size}px')
    lines.append(f'// Characters: {first_char} ({repr(chr(first_char))}) to {last_char} ({repr(chr(last_char))})')
    lines.append(f'// Total bitmap size: {len(bitmap_data)} bytes')
    lines.append(f'')
    lines.append(f'#include "aa_font.h"')
    lines.append(f'')

    # Bitmap data
    lines.append(f'static const uint8_t {font_name}_bitmap[] = {{')
    for i in range(0, len(bitmap_data), 16):
        chunk = bitmap_data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'    {hex_vals},')
    lines.append(f'}};')
    lines.append(f'')

    # Glyph array
    lines.append(f'static const AAGlyph {font_name}_glyphs[] = {{')
    for i, g in enumerate(glyph_array):
        code = first_char + i
        char_repr = repr(chr(code)) if 32 <= code < 127 else f'0x{code:02X}'
        lines.append(f'    {{ {g["width"]:3d}, {g["height"]:3d}, {g["xOffset"]:4d}, {g["yOffset"]:4d}, {g["xAdvance"]:3d}, {g["data_offset"]:5d} }},  // {char_repr}')
    lines.append(f'}};')
    lines.append(f'')

    # Font struct
    line_height = ascent + descent
    lines.append(f'static const AAFont {font_name} = {{')
    lines.append(f'    {pixel_size},  // size')
    lines.append(f'    {line_height},  // lineHeight')
    lines.append(f'    {ascent},  // ascent')
    lines.append(f'    {first_char},  // firstChar')
    lines.append(f'    {last_char},  // lastChar')
    lines.append(f'    {font_name}_glyphs,')
    lines.append(f'    {font_name}_bitmap')
    lines.append(f'}};')
    lines.append(f'')

    # Write the file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f'Generated {output_path}:')
    print(f'  Font: {os.path.basename(font_path)} @ {pixel_size}px')
    print(f'  Characters: {len(charset)} ({first_char}..{last_char})')
    print(f'  Glyph entries: {len(glyph_array)}')
    print(f'  Bitmap size: {len(bitmap_data)} bytes')
    print(f'  Line height: {line_height}, Ascent: {ascent}')


def main():
    parser = argparse.ArgumentParser(description='Generate anti-aliased font header for PD240W')
    parser.add_argument('ttf_path', help='Path to TTF font file')
    parser.add_argument('pixel_size', type=int, help='Font size in pixels')
    parser.add_argument('output_path', help='Output C header file path')
    parser.add_argument('--chars', default='ascii',
                        choices=['ascii', 'digits'],
                        help='Character set: ascii (32-126) or digits (0-9 + units)')
    parser.add_argument('--name', default=None,
                        help='C variable name prefix (default: derived from output filename)')

    args = parser.parse_args()

    if args.chars == 'digits':
        charset = CHARSET_DIGITS
    else:
        charset = CHARSET_ASCII

    if args.name is None:
        args.name = os.path.splitext(os.path.basename(args.output_path))[0]

    if not os.path.exists(args.ttf_path):
        print(f'Error: Font file not found: {args.ttf_path}')
        sys.exit(1)

    generate_header(args.ttf_path, args.pixel_size, args.output_path, charset, args.name)


if __name__ == '__main__':
    main()
